name: slack-llm-bot
message: Summarizer
image: docker.io/node:lts
resources:
  cluster: vessl-aws-seoul
  preset: cpu-medium
import:
  /app: git://github.com/vessl-ai/slack-llm-bot.git
run:
  - command: |
      npm i -g pnpm
      pnpm install 
      pnpm run start
    workdir: /app
env:
  SLACK_BOT_TOKEN:
    secret: slackbot-token
    source: secret
  SLACK_SIGNING_SECRET:
    secret: slack-signing-secret
    source: secret
  OPENAI_API_KEY:
    secret: openai-api-key
    source: secret
  OPENAI_ORGANIZATION_ID:
    secret: openai-organization-id
    source: secret
  OPENAI_PROJECT_ID:
    secret: openai-project-id
    source: secret
ports:
  - port: 3000
service:
  autoscaling:
    max: 2
    metric: cpu
    min: 1
    target: 50
  expose: 3000
